# -*- coding: utf-8 -*-
"""XGBoost_model1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bX9WxnFFri9W3fTnBP75ggDbVMZ8n4rX
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, roc_auc_score

# Loading data
df_train = pd.read_csv('/content/train_num_data.csv')
df_test = pd.read_csv('/content/test_num_data.csv')

# Isolate the target variable
y_train = df_train['label']
y_test = df_test['label']

print(df_train.shape)
print(df_test.shape)

#checking the dataframes
print(df_train.head())
print(y_train)
print(df_test.head())
print(y_test)

#encoding and normalisation
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
scaler = MinMaxScaler()

# FIT only on train, transform both
train_cat = ohe.fit_transform(df_train[['category']])
test_cat = ohe.transform(df_test[['category']])

# Process Numerical Data
num_cols = ['char_count', 'word_count', 'punct_density', 'cap_ratio', 'rating']
# FIT only on train, transform both
train_num = scaler.fit_transform(df_train[num_cols])
test_num = scaler.transform(df_test[num_cols])

# Assemble final feature matrices
X_train = np.hstack((train_cat, train_num))
X_test = np.hstack((test_cat, test_num))

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")

#checking the dataframes
print(X_train)
print(X_test)

#training the XG_Boost
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, roc_auc_score
import joblib
import pandas as pd

#Initialize and Train XGBoost
xgb_model = XGBClassifier(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    random_state=42,
    eval_metric='logloss'
)
print("Training XGBoost model...")
xgb_model.fit(X_train, y_train)

#Evaluate Performance
y_pred = xgb_model.predict(X_test)
y_proba_test = xgb_model.predict_proba(X_test)[:, 1]
y_proba_train = xgb_model.predict_proba(X_train)[:, 1]

#results of XG_Boost model
print("\n--- XGBoost Branch (Standalone) Performance ---")
print(classification_report(y_test, y_pred, target_names=['Human (OR)', 'AI (CG)']))
print(f"ROC-AUC Score: {roc_auc_score(y_test, y_proba_test):.4f}\n")

#roc- auc curve
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc


fpr, tpr, thresholds = roc_curve(y_test, y_proba_test)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'XGBoost ROC curve (AUC = {roc_auc:.4f})')

# Plot the baseline (random guessing)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Guessing (AUC = 0.5000)')

# 4. Format the plot
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate (FPR)')
plt.ylabel('True Positive Rate (TPR)')
plt.title('Receiver Operating Characteristic (ROC) - Branch B')
plt.legend(loc="lower right")
plt.grid(alpha=0.3)

# Display the plot
plt.show()

#saving probs and models
import joblib

# We save these as DataFrames so we keep the exact index alignments
train_probs_df = pd.DataFrame({'xgb_prob': y_proba_train}, index=df_train.index)
test_probs_df = pd.DataFrame({'xgb_prob': y_proba_test}, index=df_test.index)

train_probs_df.to_csv('train_xgb_probabilities.csv', index=False)
test_probs_df.to_csv('test_xgb_probabilities.csv', index=False)
print("Saved probability arrays.")

# XGBoost has a native save method which is highly efficient
xgb_model.save_model('branch_b_xgboost.json')

# We use joblib to save the fitted scaler and encoder
joblib.dump(scaler, 'branch_b_scaler.joblib')
joblib.dump(ohe, 'branch_b_ohe.joblib')
print("Saved XGBoost model, Scaler, and OneHotEncoder.")

